#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	printf "Please run script as root\n"
	exit;
fi

clear

printf "Updating package lists\n"
apt-get update

printf "Upgrading packages\n"
apt-get -y upgrade

printf "Installing security updates\n"
apt-get -y install unattended-upgrades
unattended-upgrades -d

printf "Installing ubuntu dist updates\n"
apt-get -y dist-upgrade

printf "Removing old dependencies"
apt-get -y autoremove

printf "Downloading & Installing nmap\n"
apt-get -y install nmap

printf "Running TCP scan on localhost\n"
tcpscan=$(nmap -sT localhost)

printf "Running UDP scan on localhost\n"
udpscan=$(nmap -sU localhost)

#printf "$tcpscan\n$udpscan\n"

if [[ $tcpscan = *"631/tcp open  ipp"* ]]; then
	printf "Removing cups service\n"
	apt-get -y remove cups
	apt-get -y remove cups-browsed	
	apt-get -y remove cups-daemon
fi

if [[ $udpscan = *"5353/udp open|filtered zeroconf"* ]]; then
	printf "Removing zeroconf service\n"
	apt-get -y remove avahi-daemon
fi

iptablesfilename="iptables_setup"

if [ -f $PWD/$iptablesfilename ]; then
	printf "iptables_setup script already exists\n"
else
	printf "Downloading script iptables_setup\n"
	wget https://raw.githubusercontent.com/WhiteTitanX/iptables_setup/master/iptables_setup
	chmod 755 $PWD/$iptablesfilename
fi

printf "Setting up iptables\n"
./iptables_setup

printf "\n\nNeed to reboot to finish installing updates. Press Ctrl + c to cancel\n"
sleep 5
reboot
